# This file represent simple reward policy
#   it consist of two parts: reward coefficients and done flags
---

# Reward coefficients
reward:
    # How frequently insert check-points between CVAT track points
    #   number represent distance in pixels
  track_checkpoint_expanding: 50

  # Rewards for events
  is_collided: 0.0
  is_finish: 1.0
  is_out_of_track: -1
  is_out_of_map: -1
  is_out_of_road: -1

  #
  idleness__punish_if_action_radius_less_then: 0.0
  idleness__punish_value: 0.0

  #
  new_tiles_count: 0.5
  speed_multiplication_bonus: 0.0

  speed_per_point: 0.0

  if_speed_more_then_threshold: 0.0
  speed_threshold: 0.0
  time_per_point: 0.0
  time_per_tick: 0.0

# Done flags
done:
  true_flags_to_done: ["is_out_of_road", "is_out_of_map", "is_out_of_track", "is_finish"]
  false_flags_to_done : []
...