# This file represent simple reward policy
#   it consist of two parts: reward coefficients and done flags
---

# Reward coefficients
reward:
  # How frequently insert check-points between CVAT track points
  #   number represent distance in pixels
  track_checkpoint_expanding: 50

  # Rewards for events
  is_collided: -1.0
  is_finish: 1.0
  is_out_of_track: -1.0
  new_tiles_count: 0.5

# Done flags
done:
  true_flags_to_done": ["is_out_of_road", "is_out_of_map", "is_out_of_track", "is_finish"]
...