FROM nvidia/cuda:10.0-base-ubuntu18.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        wget \
        apt-utils \
        build-essential \
        curl \
        xvfb \
        ffmpeg \
        xorg-dev \
        libsdl2-dev \
        swig \
        cmake \
        python3-pip \
        python3-dev \
        python-opengl \
        python3-setuptools

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

# install miniconda
ENV PATH="/root/miniconda3/bin:$PATH"
RUN mkdir /root/.conda && bash Miniconda3-latest-Linux-x86_64.sh -b

# create conda environment
RUN conda init bash
ADD conda_environment.yml /tmp/
RUN conda env create -f /tmp/conda_environment.yml; exit 0
RUN conda init bash
RUN /bin/bash conda activate CDS_Lab
RUN conda install -c conda-forge mpi4py

RUN apt-get -y install cuda-libraries-dev-10-0
RUN pip install -q "cupy-cuda100 ${CUPY_VERSION}"

RUN pip install torch==1.5.1+cu101

ENV OMP_NUM_THREADS=1
ENV MKL_NUM_THREADS=1

# PUT ALL CHANGES UNDER THIS LINE

RUN mkdir /src
WORKDIR /src
ADD . ./
