# This part of config s common for all agents and contain technical params.
log_interval: 20
animation_record_frequency: 100
record_animation: true

env_steps_to_run : 5000000 # 5M
max_episode_len: 500