# TD3 specific config
#track_progress_success_threshold: 0.95
start_to_learn_time_point: 25000

discount_rate: 0.99
lr: 0.00015

tau : 0.005

policy_noise : 0.2
expl_noise_linear_decay_steps: 2500000
expl_noise: 0.1
noise_clip: 0.5

policy_update_freq: 2

gradient_clipping_norm: 0.5