# Config for Rainbow parameters
---
use_parallel_envs: False
parallel_env_num: 6
track_progress_success_threshold: 0.95

# If "use_parallel_envs" == false, "num_episodes_to_run" will be used, else "num_steps_to_run"

replay_start_size: 20000
max_episode_len: 500

discount_rate: 0.99
noisy_net_sigma: 0.5

# parameters for Adam optimizer
lr: 0.0001
gradient_clipping_norm: 0.1
betas: [0.9, 0.999]
...