# Basic ppo specific config
---
use_icm: false
icm_phi: 'config.phi'
icm_gradient_clipping: 1.5

# sub param for drq
drq_padding: 2
drq_augment_num: 1 # excluding original state


num_episodes_to_run: 50
max_episode_len: 500

update_every_n_steps: 300
learning_updates_per_learning_session: 1

discount_rate: 0.99
eps_clip: 0.2  # clip parameter for PPO

# parameters for Adam optimizer
lr: 0.0001
gradient_clipping_norm: 0.3
betas: [0.9, 0.999]
...